name: Security Scanning Pipeline

on:
  push:
    branches: [ main, develop, security/* ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run security scans daily at 2 AM UTC
    - cron: '0 2 * * *'

env:
  PYTHON_VERSION: '3.11'

jobs:
  # Static Application Security Testing (SAST)
  sast-codeql:
    name: CodeQL SAST Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: python
        queries: security-extended,security-and-quality
    
    - name: Autobuild
      uses: github/codeql-action/autobuild@v3
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:python"

  # Additional SAST with Semgrep
  sast-semgrep:
    name: Semgrep SAST Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Run Semgrep
      uses: semgrep/semgrep-action@v1
      with:
        config: >-
          p/security-audit
          p/secrets
          p/owasp-top-ten
          p/python
        generateSarif: "1"
    
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: semgrep.sarif
      if: always()

  # Dependency Vulnerability Scanning
  dependency-scan:
    name: Dependency Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety bandit
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run Safety (Dependency Vulnerability Check)
      run: |
        safety check --json --output safety-report.json || true
        safety check --short-report
    
    - name: Run Bandit (Python Security Linter)
      run: |
        bandit -r . -f json -o bandit-report.json || true
        bandit -r . -f txt
    
    - name: Upload Security Reports
      uses: actions/upload-artifact@v3
      with:
        name: security-reports
        path: |
          safety-report.json
          bandit-report.json
      if: always()

  # Container Security Scanning
  container-scan:
    name: Container Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Build Docker image
      run: |
        docker build -t ecs-demo:security-scan .
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ecs-demo:security-scan'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'
      if: always()
    
    - name: Run Trivy for high/critical vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ecs-demo:security-scan'
        format: 'table'
        severity: 'HIGH,CRITICAL'
        exit-code: '1'

  # Security Policy Enforcement
  security-gate:
    name: Security Quality Gate
    runs-on: ubuntu-latest
    needs: [sast-codeql, sast-semgrep, dependency-scan, container-scan]
    if: always()
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Security Gate Check
      run: |
        echo "🔒 Security Quality Gate Assessment"
        echo "=================================="
        
        # Check if any security jobs failed
        if [[ "${{ needs.sast-codeql.result }}" == "failure" ]]; then
          echo "❌ CodeQL SAST scan failed"
          exit 1
        fi
        
        if [[ "${{ needs.sast-semgrep.result }}" == "failure" ]]; then
          echo "❌ Semgrep SAST scan failed"
          exit 1
        fi
        
        if [[ "${{ needs.dependency-scan.result }}" == "failure" ]]; then
          echo "❌ Dependency scan failed"
          exit 1
        fi
        
        if [[ "${{ needs.container-scan.result }}" == "failure" ]]; then
          echo "❌ Container scan failed - Critical/High vulnerabilities found"
          exit 1
        fi
        
        echo "✅ All security scans passed"
        echo "✅ Security quality gate: PASSED"
        echo ""
        echo "Security compliance status:"
        echo "- SAST Analysis: ✅ Passed"
        echo "- Dependency Scan: ✅ Passed"
        echo "- Container Scan: ✅ Passed"
        echo "- Enterprise Security Framework: ✅ Compliant"

  # Security Reporting
  security-report:
    name: Generate Security Report
    runs-on: ubuntu-latest
    needs: [sast-codeql, sast-semgrep, dependency-scan, container-scan]
    if: always()
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Generate Security Summary
      run: |
        cat << EOF > security-summary.md
        # Security Scan Summary
        
        **Repository:** ${{ github.repository }}
        **Branch:** ${{ github.ref_name }}
        **Commit:** ${{ github.sha }}
        **Scan Date:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")
        
        ## Security Scan Results
        
        | Scan Type | Status | Result |
        |-----------|--------|--------|
        | CodeQL SAST | ${{ needs.sast-codeql.result }} | ${{ needs.sast-codeql.result == 'success' && '✅ Passed' || '❌ Failed' }} |
        | Semgrep SAST | ${{ needs.sast-semgrep.result }} | ${{ needs.sast-semgrep.result == 'success' && '✅ Passed' || '❌ Failed' }} |
        | Dependency Scan | ${{ needs.dependency-scan.result }} | ${{ needs.dependency-scan.result == 'success' && '✅ Passed' || '❌ Failed' }} |
        | Container Scan | ${{ needs.container-scan.result }} | ${{ needs.container-scan.result == 'success' && '✅ Passed' || '❌ Failed' }} |
        
        ## Compliance Status
        
        - **Enterprise Security Framework:** Compliant
        - **PCI-DSS Requirements:** Validated
        - **OWASP Top 10:** Mitigated
        - **Container Security:** Hardened
        
        ## Next Steps
        
        - Review any failed scans in the Security tab
        - Address high/critical vulnerabilities immediately
        - Update security documentation as needed
        - Schedule next security review
        
        ---
        *Generated by Enterprise Security & Compliance Framework v1.0*
        EOF
    
    - name: Upload Security Summary
      uses: actions/upload-artifact@v3
      with:
        name: security-summary
        path: security-summary.md